version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=Prueba
      - POSTGRES_USER=pruebas
      - POSTGRES_PASSWORD=Pruebas@2022
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql